Update checkers.java
More comments, reading over the code raised some concerns about a niche situation that may cause errors, will test later
error: entering a coordinate with no piece on a free-play game could result in the empty space playing? needs testing.